### ISSUE TITLE
run proxy problem

### ISSUE THREAD

**Issue by limithsieh** [matlo/l2cap_proxy#2]
I have met a problem when running proxy.

I have paired DS4 and ps4 with my ubuntu in the first.
Then I got ds4 link key and store it in file "linkkkeys".
After that, I run "sudo ./l2cap_proxy <master-bdaddr> <dongle-bdaddr> <device-class>" and push the DS4 home button to pair.
[master-bdaddr]: ps4 bdaddr
[dongle-bdaddr]: my dongle-bdaddr
[device-class]: 0x2508

then I got message from the terminal
"
accepted connection from 30:0E:D5:8D:83:70 (psm: 0x0001)
connecting with 00:02:72:DA:2A:7B to 8C:FE:57:45:4B:4C (psm: 0x0001)
connected to 8C:FE:57:45:4B:4C (psm: 0x0001)
poll error from SLAVE (psm: 0x0001)
"
I dumped the the information and found out that the PS4 and DS4 once connect first but disconnect in the end.
I am confused with the procedure the order of pairing. Turn on DS4 first or connect to PS4 first?
Did I need to pair DS4 with PS4 before running proxy?

Thank for your great works and hope for your reply, thanks.

**Comment by matlo** [comment]
How did you pair dongle with PS4? How did you pair dongle with DS4?

**Comment by limithsieh** [comment]
I pair both PS4 and DS4 with Ubuntu bluetooth GUI.
After that the bluetoooth GUI show PS4 and DS4 are paired.

**Comment by matlo** [comment]
This paired your dongle as a network or headset device, definitely not as a DS4.

You'll find some instructions to pair your dongle as a DS4 here: https://gimx.fr/wiki/index.php?title=PS4&oldid=3287
